openapi: 3.0.2
info:
  title: MonoFlight API
  description: Microservice sample. Monolithic application sample.
  version: '1.0'
servers:
- url: http://localhost:12080
tags:
- name: Flight
  description: フライト予約サービス
paths:
  /flight:
    post:
      tags:
      - Flight
      summary: reserve flight.
      description: Reserve flights with the information from travel-reservation service.
      operationId: flight
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlightApplicationInfo'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlightReservation'
        409:
          description: No vacancies, or flight seat.
components:
  schemas:
    FlightApplicationInfo:
      title: FlightApplicationInfo
      description: the required information to reserve the flight
      type: object
      properties:
        flightName:
          type: string
          example: flightName
        departureDate:
          type: string
          format: date
          example: '2020-01-01'
        tourists:
          type: array
          items:
            type: string
            example: Saito
          description: Flights that tourists wants.
    FlightReservation:
      title: FlightReservation
      description: the information details of the reserved flight when success
      type: object
      properties:
        flightReservationId:
          type: integer
          format: int64
          example: 1
        flightName:
          type: string
          example: flightName
        departureDateTime:
          type: string
          format: date-time
          example: '2020-01-01T09:00:00+09:00'
        departureAirport:
          type: string
          example: 'HND'
        arrivalDateTime:
          type: string
          format: date-time
          example: '2020-01-01T10:30:00+09:00'
        arrivalAirport:
          type: string
          example: 'OSA'
        seatNo:
          type: string
          example: 10F