openapi: 3.0.2
info:
  title: MonoHotel API
  description: Microservice sample. Monolithic application sample.
  version: '1.0'
servers:
- url: http://localhost:11080
tags:
- name: Hotel
  description: ホテル予約サービス
paths:
  /hotel:
    post:
      tags:
      - Hotel
      summary: Reserve hotels.
      description: Reserve hotels with the information from travel-reservation service.
      operationId: hotel
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HotelApplicationInfo'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HotelReservation'
        409:
          description: No vacancies.
components:
  schemas:
    HotelApplicationInfo:
      title: HotelApplicationInfo
      description: the required information to reserve the hotel
      type: object
      properties:
        name:
          type: string
          example: Hotel Tokyo
        checkInDate:
          type: string
          format: date
          example: '2020-01-01'
        checkOutDate:
          type: string
          format: date
          example: '2020-01-02'
    HotelReservation:
      title: HotelReservation
      description: the information details of the reserved hotel when success
      type: object
      properties:
        hotelReservationId:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Hotel Tokyo
        checkInDate:
          type: string
          format: date
          example: '2020-01-01'
        checkOutDate:
          type: string
          format: date
          example: '2020-01-02'
        roomNo:
          type: string
          example: 2401
